### ISSUE TITLE
Release gem?

### ISSUE THREAD

**Issue by bbugh** [piotrmurach/tty-runner#1]
### Describe the problem

Hi! 👋🏻 I was looking for a multi-command Thor replacement and saw the link to this repo in https://github.com/piotrmurach/tty-option/issues/2. 

Had you considered releasing this? It looks good, and I'd love to use it!

### Steps to reproduce the problem

As of 2022-02-09T18:16:21Z the universe itself exists in a state of reproducing the problem of this not having an official release. 🛰️ 

### Actual behaviour

```
ERROR:  Could not find a valid gem 'tty-runner' (>= 0) in any repository
```

### Expected behaviour

`gem install tty-runner` works!

**Comment by piotrmurach** [comment]
Hi Brian,

Thanks for your support of the project.

Agree, this project needs to be released. It's not finished though. The integration with `tty-option`, in particular, needs doing to allow global options etc.

I can assure you that I'm going to work on this shortly, though I have one project I need to get done first.

In the meantime, would you have time to use and test the master branch and provide feedback?
