### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by mattmeng** [piotrmurach/tty-runner#2]
Any chance of releasing this gem?

**Comment by piotrmurach** [comment]
This gem isn't finished and isn't ready for release. It requires more work, including integration with `tty-option` and most importantly handling of dependencies in commands.

**Comment by mattmeng** [comment]
Thank you.  It has been a while and I was just wondering on the direction of this gem.  I love your TTY package and sincerely appreciate all your hard work.  It's such a pivotal toolset for me.  Thank you.
